/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContentGenerationRouteImport } from './routes/content-generation'
import { Route as ContentConsumptionRouteImport } from './routes/content-consumption'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics/$topicId'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$sourceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentGenerationRoute = ContentGenerationRouteImport.update({
  id: '/content-generation',
  path: '/content-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentConsumptionRoute = ContentConsumptionRouteImport.update({
  id: '/content-consumption',
  path: '/content-consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content-consumption': typeof ContentConsumptionRoute
  '/content-generation': typeof ContentGenerationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/sources/': typeof SourcesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content-consumption': typeof ContentConsumptionRoute
  '/content-generation': typeof ContentGenerationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/sources': typeof SourcesIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content-consumption': typeof ContentConsumptionRoute
  '/content-generation': typeof ContentGenerationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/sources/': typeof SourcesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-consumption'
    | '/content-generation'
    | '/login'
    | '/signup'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/sources/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content-consumption'
    | '/content-generation'
    | '/login'
    | '/signup'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/sources'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/content-consumption'
    | '/content-generation'
    | '/login'
    | '/signup'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/sources/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentConsumptionRoute: typeof ContentConsumptionRoute
  ContentGenerationRoute: typeof ContentGenerationRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-generation': {
      id: '/content-generation'
      path: '/content-generation'
      fullPath: '/content-generation'
      preLoaderRoute: typeof ContentGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-consumption': {
      id: '/content-consumption'
      path: '/content-consumption'
      fullPath: '/content-consumption'
      preLoaderRoute: typeof ContentConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentConsumptionRoute: ContentConsumptionRoute,
  ContentGenerationRoute: ContentGenerationRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
